import React, { useState, useEffect } from 'react';
import { useStudio } from '../../context/StudioContext';
import { useGitHub } from '../../hooks/useGitHub';
import { 
  listRepositories, 
  createRepository, 
  listBranches, 
  pushFiles,
  generateFilesForPush 
} from '../../services/githubApi';
import { Button } from '../ui/button';
import { Input } from '../ui/input';
import { Label } from '../ui/label';
import { RadioGroup, RadioGroupItem } from '../ui/radio-group';
import { Switch } from '../ui/switch';
import { ScrollArea } from '../ui/scroll-area';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
} from '../ui/dialog';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '../ui/select';
import { 
  Github, 
  Loader2, 
  FileCode2, 
  FolderGit2,
  ExternalLink,
  Search,
  Lock,
  Globe
} from 'lucide-react';
import { toast } from 'sonner';
import { Avatar, AvatarImage, AvatarFallback } from '../ui/avatar';

export function GitHubButton() {
  const { state } = useStudio();
  const { token, user, isConnected, isLoading, connect, error } = useGitHub();
  
  const [modalOpen, setModalOpen] = useState(false);
  const [isPushing, setIsPushing] = useState(false);

  const hasCode = state.preview.html || state.preview.css || state.preview.js;

  // Show error toast when there's an auth error
  useEffect(() => {
    if (error) {
      toast.error(error);
    }
  }, [error]);

  const handleClick = () => {
    if (isConnected) {
      setModalOpen(true);
    } else {
      connect();
    }
  };

  return (
    <>
      <Button
        data-testid="github-save-btn"
        variant="outline"
        onClick={handleClick}
        disabled={!hasCode || isLoading || isPushing}
        className="border-[#22222A] bg-transparent text-[#A0A0AB] hover:text-[#EDEDED] hover:bg-[#1A1A20] disabled:opacity-50"
      >
        {isLoading || isPushing ? (
          <Loader2 className="w-4 h-4 mr-2 animate-spin" />
        ) : isConnected && user ? (
          <Avatar className="w-5 h-5 mr-2">
            <AvatarImage src={user.avatar_url} alt={user.login} />
            <AvatarFallback className="text-xs bg-[#19AFFF]/20 text-[#19AFFF]">
              {user.login?.[0]?.toUpperCase()}
            </AvatarFallback>
          </Avatar>
        ) : (
          <Github className="w-4 h-4 mr-2" />
        )}
        {isPushing ? 'Pushing...' : isConnected ? 'Push to GitHub' : 'Save to GitHub'}
      </Button>

      {isConnected && (
        <GitHubPushModal
          isOpen={modalOpen}
          onClose={() => setModalOpen(false)}
          token={token}
          user={user}
          preview={state.preview}
          onPushing={setIsPushing}
        />
      )}
    </>
  );
}

function GitHubPushModal({ isOpen, onClose, token, user, preview, onPushing }) {
  const [mode, setMode] = useState('existing'); // 'existing' | 'new'
  const [repos, setRepos] = useState([]);
  const [branches, setBranches] = useState([]);
  const [loadingRepos, setLoadingRepos] = useState(false);
  const [loadingBranches, setLoadingBranches] = useState(false);
  const [isPushing, setIsPushing] = useState(false);
  
  // Form state
  const [selectedRepo, setSelectedRepo] = useState('');
  const [selectedBranch, setSelectedBranch] = useState('');
  const [repoSearch, setRepoSearch] = useState('');
  const [newRepoName, setNewRepoName] = useState('');
  const [newRepoDescription, setNewRepoDescription] = useState('Generated by Cartola Lab Studio');
  const [isPrivate, setIsPrivate] = useState(false);
  const [filePath, setFilePath] = useState('/');
  const [commitMessage, setCommitMessage] = useState('feat: app from Cartola Lab Studio');

  // Load repositories on mount
  useEffect(() => {
    if (isOpen && token) {
      loadRepos();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [isOpen, token]);

  // Load branches when repo is selected
  useEffect(() => {
    if (selectedRepo && token) {
      loadBranches(selectedRepo);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [selectedRepo, token]);

  const loadRepos = async () => {
    setLoadingRepos(true);
    try {
      const repoList = await listRepositories(token);
      setRepos(repoList);
    } catch (err) {
      toast.error('Failed to load repositories');
    } finally {
      setLoadingRepos(false);
    }
  };

  const loadBranches = async (repoFullName) => {
    setLoadingBranches(true);
    try {
      const [owner, repo] = repoFullName.split('/');
      const branchList = await listBranches(token, owner, repo);
      setBranches(branchList);
      if (branchList.length > 0 && !branchList.includes(selectedBranch)) {
        setSelectedBranch(branchList[0]);
      }
    } catch (err) {
      toast.error('Failed to load branches');
    } finally {
      setLoadingBranches(false);
    }
  };

  const handlePush = async () => {
    setIsPushing(true);
    onPushing(true);

    try {
      let targetRepo = selectedRepo;

      // Create new repo if needed
      if (mode === 'new') {
        if (!newRepoName.trim()) {
          toast.error('Please enter a repository name');
          return;
        }

        const newRepo = await createRepository(
          token,
          newRepoName.trim(),
          newRepoDescription,
          isPrivate
        );
        
        targetRepo = newRepo.full_name;
        
        // Wait a bit for GitHub to initialize the repo
        await new Promise(resolve => setTimeout(resolve, 2000));
        
        // Reload branches for new repo
        const branchList = await listBranches(token, user.login, newRepo.name);
        if (branchList.length > 0) {
          setSelectedBranch(branchList[0]);
        }
      }

      if (!targetRepo) {
        toast.error('Please select or create a repository');
        return;
      }

      // Generate files
      const files = generateFilesForPush(preview);

      // Push to GitHub
      const result = await pushFiles(token, {
        repo: targetRepo,
        branch: selectedBranch || 'main',
        path: filePath,
        commitMessage,
        files
      });

      toast.success(
        <div className="flex flex-col gap-1">
          <span>Pushed to GitHub!</span>
          <a 
            href={result.html_url} 
            target="_blank" 
            rel="noopener noreferrer"
            className="text-[#19AFFF] flex items-center gap-1 hover:underline"
          >
            View commit <ExternalLink className="w-3 h-3" />
          </a>
        </div>,
        { duration: 8000 }
      );

      onClose();
    } catch (err) {
      toast.error(err.message);
    } finally {
      setIsPushing(false);
      onPushing(false);
    }
  };

  const filteredRepos = repos.filter(repo => 
    repo.name.toLowerCase().includes(repoSearch.toLowerCase()) ||
    repo.full_name.toLowerCase().includes(repoSearch.toLowerCase())
  );

  const files = generateFilesForPush(preview);

  return (
    <Dialog open={isOpen} onOpenChange={(open) => !open && onClose()}>
      <DialogContent className="bg-[#111115] border-[#22222A] text-[#EDEDED] max-w-lg max-h-[90vh] overflow-hidden flex flex-col">
        <DialogHeader>
          <DialogTitle className="text-xl font-semibold flex items-center gap-2">
            <Github className="w-5 h-5" />
            Push to GitHub
          </DialogTitle>
          <DialogDescription className="text-[#A0A0AB]">
            Save your generated code to a GitHub repository.
          </DialogDescription>
        </DialogHeader>

        <ScrollArea className="flex-1 pr-4">
          <div className="space-y-5 py-4">
            {/* Repository Mode Selection */}
            <RadioGroup value={mode} onValueChange={setMode} className="space-y-2">
              <div className="flex items-center space-x-2">
                <RadioGroupItem value="existing" id="existing" className="border-[#22222A] text-[#19AFFF]" />
                <Label htmlFor="existing" className="text-[#EDEDED] cursor-pointer">Push to existing repository</Label>
              </div>
              <div className="flex items-center space-x-2">
                <RadioGroupItem value="new" id="new" className="border-[#22222A] text-[#19AFFF]" />
                <Label htmlFor="new" className="text-[#EDEDED] cursor-pointer">Create new repository</Label>
              </div>
            </RadioGroup>

            {mode === 'existing' ? (
              <>
                {/* Repository Search/Select */}
                <div className="space-y-2">
                  <Label className="text-xs text-[#6A6A75] uppercase tracking-wider">Repository</Label>
                  <div className="relative">
                    <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-[#6A6A75]" />
                    <Input
                      data-testid="repo-search-input"
                      placeholder="Search repositories..."
                      value={repoSearch}
                      onChange={(e) => setRepoSearch(e.target.value)}
                      className="pl-9 bg-[#0A0A0A] border-[#22222A] text-[#EDEDED] placeholder:text-[#6A6A75]"
                    />
                  </div>
                  {loadingRepos ? (
                    <div className="flex items-center justify-center py-4">
                      <Loader2 className="w-5 h-5 animate-spin text-[#19AFFF]" />
                    </div>
                  ) : (
                    <div className="max-h-32 overflow-y-auto border border-[#22222A] rounded-md bg-[#0A0A0A]">
                      {filteredRepos.length === 0 ? (
                        <div className="p-3 text-sm text-[#6A6A75] text-center">No repositories found</div>
                      ) : (
                        filteredRepos.map((repo) => (
                          <button
                            key={repo.id}
                            onClick={() => setSelectedRepo(repo.full_name)}
                            className={`
                              w-full px-3 py-2 text-left flex items-center gap-2 text-sm
                              ${selectedRepo === repo.full_name 
                                ? 'bg-[#19AFFF]/10 text-[#19AFFF]' 
                                : 'text-[#A0A0AB] hover:bg-[#1A1A20] hover:text-[#EDEDED]'}
                            `}
                          >
                            <FolderGit2 className="w-4 h-4 shrink-0" />
                            <span className="truncate">{repo.full_name}</span>
                            {repo.private && <Lock className="w-3 h-3 shrink-0 text-[#6A6A75]" />}
                          </button>
                        ))
                      )}
                    </div>
                  )}
                </div>

                {/* Branch Select */}
                {selectedRepo && (
                  <div className="space-y-2">
                    <Label className="text-xs text-[#6A6A75] uppercase tracking-wider">Branch</Label>
                    <Select 
                      value={selectedBranch} 
                      onValueChange={setSelectedBranch}
                      disabled={loadingBranches}
                    >
                      <SelectTrigger 
                        data-testid="branch-select"
                        className="bg-[#0A0A0A] border-[#22222A] text-[#EDEDED]"
                      >
                        <SelectValue placeholder={loadingBranches ? "Loading..." : "Select branch"} />
                      </SelectTrigger>
                      <SelectContent className="bg-[#111115] border-[#22222A]">
                        {branches.map((branch) => (
                          <SelectItem 
                            key={branch} 
                            value={branch}
                            className="text-[#EDEDED] focus:bg-[#1A1A20] focus:text-[#EDEDED]"
                          >
                            {branch}
                          </SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                  </div>
                )}
              </>
            ) : (
              <>
                {/* New Repository Form */}
                <div className="space-y-2">
                  <Label className="text-xs text-[#6A6A75] uppercase tracking-wider">Repository name</Label>
                  <Input
                    data-testid="new-repo-name"
                    placeholder="my-app-name"
                    value={newRepoName}
                    onChange={(e) => setNewRepoName(e.target.value)}
                    className="bg-[#0A0A0A] border-[#22222A] text-[#EDEDED] placeholder:text-[#6A6A75]"
                  />
                </div>

                <div className="space-y-2">
                  <Label className="text-xs text-[#6A6A75] uppercase tracking-wider">Description</Label>
                  <Input
                    data-testid="new-repo-description"
                    placeholder="Generated by Cartola Lab Studio"
                    value={newRepoDescription}
                    onChange={(e) => setNewRepoDescription(e.target.value)}
                    className="bg-[#0A0A0A] border-[#22222A] text-[#EDEDED] placeholder:text-[#6A6A75]"
                  />
                </div>

                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    {isPrivate ? (
                      <Lock className="w-4 h-4 text-[#A0A0AB]" />
                    ) : (
                      <Globe className="w-4 h-4 text-[#A0A0AB]" />
                    )}
                    <Label className="text-[#EDEDED]">
                      {isPrivate ? 'Private' : 'Public'}
                    </Label>
                  </div>
                  <Switch
                    checked={isPrivate}
                    onCheckedChange={setIsPrivate}
                    className="data-[state=checked]:bg-[#19AFFF]"
                  />
                </div>
              </>
            )}

            {/* Path */}
            <div className="space-y-2">
              <Label className="text-xs text-[#6A6A75] uppercase tracking-wider">Path</Label>
              <Input
                data-testid="file-path-input"
                placeholder="/"
                value={filePath}
                onChange={(e) => setFilePath(e.target.value)}
                className="bg-[#0A0A0A] border-[#22222A] text-[#EDEDED] placeholder:text-[#6A6A75]"
              />
            </div>

            {/* Commit Message */}
            <div className="space-y-2">
              <Label className="text-xs text-[#6A6A75] uppercase tracking-wider">Commit message</Label>
              <Input
                data-testid="commit-message-input"
                placeholder="feat: app from Cartola Lab Studio"
                value={commitMessage}
                onChange={(e) => setCommitMessage(e.target.value)}
                className="bg-[#0A0A0A] border-[#22222A] text-[#EDEDED] placeholder:text-[#6A6A75]"
              />
            </div>

            {/* Files Preview */}
            <div className="space-y-2">
              <Label className="text-xs text-[#6A6A75] uppercase tracking-wider">Files to push</Label>
              <div className="border border-[#22222A] rounded-md bg-[#0A0A0A] divide-y divide-[#22222A]">
                {files.map((file) => (
                  <div key={file.name} className="flex items-center justify-between px-3 py-2">
                    <div className="flex items-center gap-2 text-sm text-[#A0A0AB]">
                      <FileCode2 className="w-4 h-4" />
                      <span>{file.name}</span>
                    </div>
                    <span className="text-xs text-[#6A6A75]">
                      {(file.content.length / 1024).toFixed(1)} KB
                    </span>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </ScrollArea>

        <DialogFooter className="pt-4 border-t border-[#22222A]">
          <Button
            variant="outline"
            onClick={onClose}
            disabled={isPushing}
            className="border-[#22222A] text-[#A0A0AB] hover:text-[#EDEDED]"
          >
            Cancel
          </Button>
          <Button
            data-testid="github-push-confirm-btn"
            onClick={handlePush}
            disabled={isPushing || (mode === 'existing' && !selectedRepo) || (mode === 'new' && !newRepoName.trim())}
            className="bg-[#19AFFF] hover:bg-[#40BDFF] text-white"
          >
            {isPushing ? (
              <>
                <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                Pushing...
              </>
            ) : (
              <>
                <Github className="w-4 h-4 mr-2" />
                Push to GitHub
              </>
            )}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

export default GitHubButton;
